Completely remove DispatchContext
invenia/Dispatcher.jl pull request #26
Opened 2017-08-03 21:21 UTC by iamed2

I figure this is still okay to do in one shot since we're pre-1.0.

@rofinn please review when you can

@nicoleepp please let me know if you were relying on anything I removed

2017-08-04 15:58 UTC, nicoleepp approved these changes
Doesn't affect anything being relied on for `DaskDistributedDispatcher.jl`.

2017-08-08 16:27 UTC, rofinn requested changes
This seems a lot cleaner.

2017-08-08 16:27 UTC, rofinn commented on src/executors.jl
> +function build_graph{T<:DispatchNode, S<:DispatchNode}(
Could these just be `DispatchGraph` constructors to minimize cluttering up the namespace?

2017-08-08 16:27 UTC, rofinn commented on test/runtests.jl
> +                    b = Op(
Might be cleaner to write these as do-blocks.

2017-08-08 16:27 UTC, rofinn commented on src/executors.jl
> +Then `dispatch!(exec, ctx.graph)` will throw a `DependencyError` and
`ctx.graph` -> `graph`.

2017-08-08 16:27 UTC, rofinn commented on src/executors.jl
>  `dispatch!(exec, ctx; throw_error=false)` will return an array of passing nodes and the
`ctx` -> `graph`

2017-08-08 16:27 UTC, rofinn commented on src/executors.jl
> +`dispatch!(exec, ctx.graph)` will return [n1, n2, http_node].
`ctx.graph` -> `graph`

2017-08-08 16:27 UTC, rofinn commented on docs/src/pages/api.md
>  dispatch!(::Executor, ::DispatchContext)
`DispatchContext` -> `DispatchGraph`

2017-08-09 17:29 UTC, rofinn approved these changes

2017-08-10 00:28 UTC, merged